version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - straight2prod
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER={DB_USER}
      - POSTGRES_PASSWORD={DB_PASSWORD}
      - POSTGRES_DB={DB_NAME}
      - POSTGRES_PORT={DB_PORT}
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - straight2prod

volumes:
  data:

networks:
  straight2prod:
    name: straight2prod
    
